// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/session/types.proto

package session

import (
	acl "github.com/nspcc-dev/neofs-sdk-go/proto/acl"
	refs "github.com/nspcc-dev/neofs-sdk-go/proto/refs"
	status "github.com/nspcc-dev/neofs-sdk-go/proto/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verb represents all possible operations in NeoFS that can be authorized
// via session tokens or delegation chains. This enum covers both object and
// container service operations.
type Verb int32

const (
	// Unknown verb
	Verb_VERB_UNSPECIFIED Verb = 0
	// Refers to object.Put RPC call
	Verb_OBJECT_PUT Verb = 1
	// Refers to object.Get RPC call
	Verb_OBJECT_GET Verb = 2
	// Refers to object.Head RPC call
	Verb_OBJECT_HEAD Verb = 3
	// Refers to object.Search RPC call
	Verb_OBJECT_SEARCH Verb = 4
	// Refers to object.Delete RPC call
	Verb_OBJECT_DELETE Verb = 5
	// Refers to object.GetRange RPC call
	Verb_OBJECT_RANGE Verb = 6
	// Refers to object.GetRangeHash RPC call
	Verb_OBJECT_RANGEHASH Verb = 7
	// Refers to container.Put RPC call
	Verb_CONTAINER_PUT Verb = 8
	// Refers to container.Delete RPC call
	Verb_CONTAINER_DELETE Verb = 9
	// Refers to container.SetExtendedACL RPC call
	Verb_CONTAINER_SETEACL Verb = 10
	// Refers to container.SetAttribute RPC call
	Verb_CONTAINER_SETATTRIBUTE Verb = 11
	// Refers to container.RemoveAttribute RPC call
	Verb_CONTAINER_REMOVEATTRIBUTE Verb = 12
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0:  "VERB_UNSPECIFIED",
		1:  "OBJECT_PUT",
		2:  "OBJECT_GET",
		3:  "OBJECT_HEAD",
		4:  "OBJECT_SEARCH",
		5:  "OBJECT_DELETE",
		6:  "OBJECT_RANGE",
		7:  "OBJECT_RANGEHASH",
		8:  "CONTAINER_PUT",
		9:  "CONTAINER_DELETE",
		10: "CONTAINER_SETEACL",
		11: "CONTAINER_SETATTRIBUTE",
		12: "CONTAINER_REMOVEATTRIBUTE",
	}
	Verb_value = map[string]int32{
		"VERB_UNSPECIFIED":          0,
		"OBJECT_PUT":                1,
		"OBJECT_GET":                2,
		"OBJECT_HEAD":               3,
		"OBJECT_SEARCH":             4,
		"OBJECT_DELETE":             5,
		"OBJECT_RANGE":              6,
		"OBJECT_RANGEHASH":          7,
		"CONTAINER_PUT":             8,
		"CONTAINER_DELETE":          9,
		"CONTAINER_SETEACL":         10,
		"CONTAINER_SETATTRIBUTE":    11,
		"CONTAINER_REMOVEATTRIBUTE": 12,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_types_proto_enumTypes[0].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_proto_session_types_proto_enumTypes[0]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{0}
}

// Object request verbs
type ObjectSessionContext_Verb int32

const (
	// Unknown verb
	ObjectSessionContext_VERB_UNSPECIFIED ObjectSessionContext_Verb = 0
	// Refers to object.Put RPC call
	ObjectSessionContext_PUT ObjectSessionContext_Verb = 1
	// Refers to object.Get RPC call
	ObjectSessionContext_GET ObjectSessionContext_Verb = 2
	// Refers to object.Head RPC call
	ObjectSessionContext_HEAD ObjectSessionContext_Verb = 3
	// Refers to object.Search RPC call
	ObjectSessionContext_SEARCH ObjectSessionContext_Verb = 4
	// Refers to object.Delete RPC call
	ObjectSessionContext_DELETE ObjectSessionContext_Verb = 5
	// Refers to object.GetRange RPC call
	ObjectSessionContext_RANGE ObjectSessionContext_Verb = 6
	// Refers to object.GetRangeHash RPC call
	ObjectSessionContext_RANGEHASH ObjectSessionContext_Verb = 7
)

// Enum value maps for ObjectSessionContext_Verb.
var (
	ObjectSessionContext_Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "PUT",
		2: "GET",
		3: "HEAD",
		4: "SEARCH",
		5: "DELETE",
		6: "RANGE",
		7: "RANGEHASH",
	}
	ObjectSessionContext_Verb_value = map[string]int32{
		"VERB_UNSPECIFIED": 0,
		"PUT":              1,
		"GET":              2,
		"HEAD":             3,
		"SEARCH":           4,
		"DELETE":           5,
		"RANGE":            6,
		"RANGEHASH":        7,
	}
)

func (x ObjectSessionContext_Verb) Enum() *ObjectSessionContext_Verb {
	p := new(ObjectSessionContext_Verb)
	*p = x
	return p
}

func (x ObjectSessionContext_Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectSessionContext_Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_types_proto_enumTypes[1].Descriptor()
}

func (ObjectSessionContext_Verb) Type() protoreflect.EnumType {
	return &file_proto_session_types_proto_enumTypes[1]
}

func (x ObjectSessionContext_Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectSessionContext_Verb.Descriptor instead.
func (ObjectSessionContext_Verb) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{0, 0}
}

// Container request verbs
type ContainerSessionContext_Verb int32

const (
	// Unknown verb
	ContainerSessionContext_VERB_UNSPECIFIED ContainerSessionContext_Verb = 0
	// Refers to container.Put RPC call
	ContainerSessionContext_PUT ContainerSessionContext_Verb = 1
	// Refers to container.Delete RPC call
	ContainerSessionContext_DELETE ContainerSessionContext_Verb = 2
	// Refers to container.SetExtendedACL RPC call
	ContainerSessionContext_SETEACL ContainerSessionContext_Verb = 3
	// Refers to container.SetAttribute RPC call
	ContainerSessionContext_SETATTRIBUTE ContainerSessionContext_Verb = 4
	// Refers to container.RemoveAttribute RPC call
	ContainerSessionContext_REMOVEATTRIBUTE ContainerSessionContext_Verb = 5
)

// Enum value maps for ContainerSessionContext_Verb.
var (
	ContainerSessionContext_Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
		3: "SETEACL",
		4: "SETATTRIBUTE",
		5: "REMOVEATTRIBUTE",
	}
	ContainerSessionContext_Verb_value = map[string]int32{
		"VERB_UNSPECIFIED": 0,
		"PUT":              1,
		"DELETE":           2,
		"SETEACL":          3,
		"SETATTRIBUTE":     4,
		"REMOVEATTRIBUTE":  5,
	}
)

func (x ContainerSessionContext_Verb) Enum() *ContainerSessionContext_Verb {
	p := new(ContainerSessionContext_Verb)
	*p = x
	return p
}

func (x ContainerSessionContext_Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerSessionContext_Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_types_proto_enumTypes[2].Descriptor()
}

func (ContainerSessionContext_Verb) Type() protoreflect.EnumType {
	return &file_proto_session_types_proto_enumTypes[2]
}

func (x ContainerSessionContext_Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerSessionContext_Verb.Descriptor instead.
func (ContainerSessionContext_Verb) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{1, 0}
}

// Context information for Session Tokens related to ObjectService requests
type ObjectSessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of request for which the token is issued
	Verb ObjectSessionContext_Verb `protobuf:"varint,1,opt,name=verb,proto3,enum=neo.fs.v2.session.ObjectSessionContext_Verb" json:"verb,omitempty"`
	// Object session target. MUST be correctly formed and set. If `objects`
	// field is not empty, then the session applies only to these elements,
	// otherwise, to all objects from the specified container.
	Target        *ObjectSessionContext_Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectSessionContext) Reset() {
	*x = ObjectSessionContext{}
	mi := &file_proto_session_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectSessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSessionContext) ProtoMessage() {}

func (x *ObjectSessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSessionContext.ProtoReflect.Descriptor instead.
func (*ObjectSessionContext) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectSessionContext) GetVerb() ObjectSessionContext_Verb {
	if x != nil {
		return x.Verb
	}
	return ObjectSessionContext_VERB_UNSPECIFIED
}

func (x *ObjectSessionContext) GetTarget() *ObjectSessionContext_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

// Context information for Session Tokens related to ContainerService requests.
type ContainerSessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of request for which the token is issued
	Verb ContainerSessionContext_Verb `protobuf:"varint,1,opt,name=verb,proto3,enum=neo.fs.v2.session.ContainerSessionContext_Verb" json:"verb,omitempty"`
	// Spreads the action to all owner containers.
	// If set, container_id field is ignored.
	Wildcard bool `protobuf:"varint,2,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	// Particular container to which the action applies.
	// Ignored if wildcard flag is set.
	ContainerId   *refs.ContainerID `protobuf:"bytes,3,opt,name=container_id,json=containerID,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSessionContext) Reset() {
	*x = ContainerSessionContext{}
	mi := &file_proto_session_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSessionContext) ProtoMessage() {}

func (x *ContainerSessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSessionContext.ProtoReflect.Descriptor instead.
func (*ContainerSessionContext) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerSessionContext) GetVerb() ContainerSessionContext_Verb {
	if x != nil {
		return x.Verb
	}
	return ContainerSessionContext_VERB_UNSPECIFIED
}

func (x *ContainerSessionContext) GetWildcard() bool {
	if x != nil {
		return x.Wildcard
	}
	return false
}

func (x *ContainerSessionContext) GetContainerId() *refs.ContainerID {
	if x != nil {
		return x.ContainerId
	}
	return nil
}

// NeoFS Session Token.
type SessionToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session Token contains the proof of trust between peers to be attached in
	// requests for further verification. Please see corresponding section of
	// NeoFS Technical Specification for details.
	Body *SessionToken_Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Signature of `SessionToken` information
	Signature     *refs.Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken) Reset() {
	*x = SessionToken{}
	mi := &file_proto_session_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken) ProtoMessage() {}

func (x *SessionToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken.ProtoReflect.Descriptor instead.
func (*SessionToken) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{2}
}

func (x *SessionToken) GetBody() *SessionToken_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SessionToken) GetSignature() *refs.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Extended headers for Request/Response. They may contain any user-defined headers
// to be interpreted on application level.
//
// Key name must be a unique valid UTF-8 string. Value can't be empty. Requests or
// Responses with duplicated header names or headers with empty values will be
// considered invalid.
//
// There are some "well-known" headers starting with `__NEOFS__` prefix that
// affect system behaviour:
//
//   - __NEOFS__NETMAP_EPOCH \
//     Netmap epoch to use for object placement calculation. The `value` is string
//     encoded `uint64` in decimal presentation. If set to '0' or not set, the
//     current epoch only will be used. DEPRECATED: header ignored by servers.
//   - __NEOFS__NETMAP_LOOKUP_DEPTH \
//     If object can't be found using current epoch's netmap, this header limits
//     how many past epochs the node can look up through. The `value` is string
//     encoded `uint64` in decimal presentation. If set to '0' or not set, only the
//     current epoch will be used. DEPRECATED: header ignored by servers.
type XHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the X-Header
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value of the X-Header
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XHeader) Reset() {
	*x = XHeader{}
	mi := &file_proto_session_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XHeader) ProtoMessage() {}

func (x *XHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XHeader.ProtoReflect.Descriptor instead.
func (*XHeader) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{3}
}

func (x *XHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *XHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Meta information attached to the request. When forwarded between peers,
// request meta headers are folded in matryoshka style.
type RequestMetaHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer's API version used
	Version *refs.Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Peer's local epoch number. Set to 0 if unknown.
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Maximum number of intermediate nodes in the request route
	Ttl uint32 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Request X-Headers
	XHeaders []*XHeader `protobuf:"bytes,4,rep,name=x_headers,json=xHeaders,proto3" json:"x_headers,omitempty"`
	// Session token within which the request is sent
	SessionToken *SessionToken `protobuf:"bytes,5,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Session token v2 with delegation chain support.
	// Requests are invalid if both session_token and session_token_v2 are set.
	SessionTokenV2 *SessionTokenV2 `protobuf:"bytes,9,opt,name=session_token_v2,json=sessionTokenV2,proto3" json:"session_token_v2,omitempty"`
	// `BearerToken` with eACL overrides for the request
	BearerToken *acl.BearerToken `protobuf:"bytes,6,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	// `RequestMetaHeader` of the origin request
	Origin *RequestMetaHeader `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	// NeoFS network magic. Must match the value for the network
	// that the server belongs to.
	MagicNumber   uint64 `protobuf:"varint,8,opt,name=magic_number,json=magicNumber,proto3" json:"magic_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetaHeader) Reset() {
	*x = RequestMetaHeader{}
	mi := &file_proto_session_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetaHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetaHeader) ProtoMessage() {}

func (x *RequestMetaHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetaHeader.ProtoReflect.Descriptor instead.
func (*RequestMetaHeader) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMetaHeader) GetVersion() *refs.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RequestMetaHeader) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RequestMetaHeader) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *RequestMetaHeader) GetXHeaders() []*XHeader {
	if x != nil {
		return x.XHeaders
	}
	return nil
}

func (x *RequestMetaHeader) GetSessionToken() *SessionToken {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *RequestMetaHeader) GetSessionTokenV2() *SessionTokenV2 {
	if x != nil {
		return x.SessionTokenV2
	}
	return nil
}

func (x *RequestMetaHeader) GetBearerToken() *acl.BearerToken {
	if x != nil {
		return x.BearerToken
	}
	return nil
}

func (x *RequestMetaHeader) GetOrigin() *RequestMetaHeader {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *RequestMetaHeader) GetMagicNumber() uint64 {
	if x != nil {
		return x.MagicNumber
	}
	return 0
}

// Information about the response
type ResponseMetaHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer's API version used
	Version *refs.Version `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Peer's local epoch number
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Maximum number of intermediate nodes in the request route
	Ttl uint32 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Response X-Headers
	XHeaders []*XHeader `protobuf:"bytes,4,rep,name=x_headers,json=xHeaders,proto3" json:"x_headers,omitempty"`
	// `ResponseMetaHeader` of the origin request
	Origin *ResponseMetaHeader `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	// Status return
	Status        *status.Status `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMetaHeader) Reset() {
	*x = ResponseMetaHeader{}
	mi := &file_proto_session_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetaHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetaHeader) ProtoMessage() {}

func (x *ResponseMetaHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMetaHeader.ProtoReflect.Descriptor instead.
func (*ResponseMetaHeader) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMetaHeader) GetVersion() *refs.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ResponseMetaHeader) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ResponseMetaHeader) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ResponseMetaHeader) GetXHeaders() []*XHeader {
	if x != nil {
		return x.XHeaders
	}
	return nil
}

func (x *ResponseMetaHeader) GetOrigin() *ResponseMetaHeader {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ResponseMetaHeader) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// Verification info for the request signed by all intermediate nodes.
type RequestVerificationHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request Body signature. Should be generated once by the request initiator.
	BodySignature *refs.Signature `protobuf:"bytes,1,opt,name=body_signature,json=bodySignature,proto3" json:"body_signature,omitempty"`
	// Request Meta signature is added and signed by each intermediate node
	MetaSignature *refs.Signature `protobuf:"bytes,2,opt,name=meta_signature,json=metaSignature,proto3" json:"meta_signature,omitempty"`
	// Signature of previous hops
	OriginSignature *refs.Signature `protobuf:"bytes,3,opt,name=origin_signature,json=originSignature,proto3" json:"origin_signature,omitempty"`
	// Chain of previous hops signatures
	Origin        *RequestVerificationHeader `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVerificationHeader) Reset() {
	*x = RequestVerificationHeader{}
	mi := &file_proto_session_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVerificationHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVerificationHeader) ProtoMessage() {}

func (x *RequestVerificationHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVerificationHeader.ProtoReflect.Descriptor instead.
func (*RequestVerificationHeader) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{6}
}

func (x *RequestVerificationHeader) GetBodySignature() *refs.Signature {
	if x != nil {
		return x.BodySignature
	}
	return nil
}

func (x *RequestVerificationHeader) GetMetaSignature() *refs.Signature {
	if x != nil {
		return x.MetaSignature
	}
	return nil
}

func (x *RequestVerificationHeader) GetOriginSignature() *refs.Signature {
	if x != nil {
		return x.OriginSignature
	}
	return nil
}

func (x *RequestVerificationHeader) GetOrigin() *RequestVerificationHeader {
	if x != nil {
		return x.Origin
	}
	return nil
}

// Verification info for the response signed by all intermediate nodes
type ResponseVerificationHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response Body signature. Should be generated once by an answering node.
	BodySignature *refs.Signature `protobuf:"bytes,1,opt,name=body_signature,json=bodySignature,proto3" json:"body_signature,omitempty"`
	// Response Meta signature is added and signed by each intermediate node
	MetaSignature *refs.Signature `protobuf:"bytes,2,opt,name=meta_signature,json=metaSignature,proto3" json:"meta_signature,omitempty"`
	// Signature of previous hops
	OriginSignature *refs.Signature `protobuf:"bytes,3,opt,name=origin_signature,json=originSignature,proto3" json:"origin_signature,omitempty"`
	// Chain of previous hops signatures
	Origin        *ResponseVerificationHeader `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseVerificationHeader) Reset() {
	*x = ResponseVerificationHeader{}
	mi := &file_proto_session_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseVerificationHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVerificationHeader) ProtoMessage() {}

func (x *ResponseVerificationHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVerificationHeader.ProtoReflect.Descriptor instead.
func (*ResponseVerificationHeader) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseVerificationHeader) GetBodySignature() *refs.Signature {
	if x != nil {
		return x.BodySignature
	}
	return nil
}

func (x *ResponseVerificationHeader) GetMetaSignature() *refs.Signature {
	if x != nil {
		return x.MetaSignature
	}
	return nil
}

func (x *ResponseVerificationHeader) GetOriginSignature() *refs.Signature {
	if x != nil {
		return x.OriginSignature
	}
	return nil
}

func (x *ResponseVerificationHeader) GetOrigin() *ResponseVerificationHeader {
	if x != nil {
		return x.Origin
	}
	return nil
}

// Target account for SessionTokenV2.
// It can be either direct (OwnerID) or indirect (NNS domain).
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account identifier.
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*Target_OwnerId
	//	*Target_NnsName
	Identifier    isTarget_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_proto_session_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{8}
}

func (x *Target) GetIdentifier() isTarget_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Target) GetOwnerId() *refs.OwnerID {
	if x != nil {
		if x, ok := x.Identifier.(*Target_OwnerId); ok {
			return x.OwnerId
		}
	}
	return nil
}

func (x *Target) GetNnsName() string {
	if x != nil {
		if x, ok := x.Identifier.(*Target_NnsName); ok {
			return x.NnsName
		}
	}
	return ""
}

type isTarget_Identifier interface {
	isTarget_Identifier()
}

type Target_OwnerId struct {
	// Direct account reference via OwnerID (hash of verification script).
	OwnerId *refs.OwnerID `protobuf:"bytes,1,opt,name=owner_id,json=ownerID,proto3,oneof"`
}

type Target_NnsName struct {
	// Indirect account reference via NeoFS Name Service.
	// NNS name is a domain name that resolves to an OwnerID through the
	// NeoFS Name Service. The name must be a valid DNS-like domain name
	// (e.g., "example.neofs") that is registered in the NNS contract on
	// the Neo blockchain. The NNS record should contain a string record with
	// the corresponding OwnerID value in NEP-18 address format.
	NnsName string `protobuf:"bytes,2,opt,name=nns_name,json=nnsName,proto3,oneof"`
}

func (*Target_OwnerId) isTarget_Identifier() {}

func (*Target_NnsName) isTarget_Identifier() {}

// Lifetime parameters of the token v2. Field names taken from rfc7519.
type TokenLifetime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expiration, the last valid Unix timestamp.
	Exp uint64 `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	// Not valid before, the first valid Unix timestamp.
	Nbf uint64 `protobuf:"varint,2,opt,name=nbf,proto3" json:"nbf,omitempty"`
	// Issued at, the Unix timestamp when the token was issued.
	Iat           uint64 `protobuf:"varint,3,opt,name=iat,proto3" json:"iat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenLifetime) Reset() {
	*x = TokenLifetime{}
	mi := &file_proto_session_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenLifetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenLifetime) ProtoMessage() {}

func (x *TokenLifetime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenLifetime.ProtoReflect.Descriptor instead.
func (*TokenLifetime) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{9}
}

func (x *TokenLifetime) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *TokenLifetime) GetNbf() uint64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *TokenLifetime) GetIat() uint64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

// SessionContextV2 carries unified context for both ObjectService and ContainerService requests.
type SessionContextV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container where operation is allowed.
	// For container operations, this is the container being operated on.
	// For object operations, this is the container holding the objects.
	// Empty container ID means wildcard (applies to all containers).
	Container *refs.ContainerID `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// Operations authorized for this context.
	// Must contain at least one verb (empty list is invalid).
	// Verbs must be sorted in ascending order.
	// Maximum number of verbs: 12.
	Verbs         []Verb `protobuf:"varint,2,rep,packed,name=verbs,proto3,enum=neo.fs.v2.session.Verb" json:"verbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContextV2) Reset() {
	*x = SessionContextV2{}
	mi := &file_proto_session_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContextV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContextV2) ProtoMessage() {}

func (x *SessionContextV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContextV2.ProtoReflect.Descriptor instead.
func (*SessionContextV2) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{10}
}

func (x *SessionContextV2) GetContainer() *refs.ContainerID {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *SessionContextV2) GetVerbs() []Verb {
	if x != nil {
		return x.Verbs
	}
	return nil
}

// SessionTokenV2 represents NeoFS Session Token with delegation support.
type SessionTokenV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token body.
	Body *SessionTokenV2_Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// Signature of the body by the issuer.
	Signature *refs.Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Origin token that was delegated to create this token.
	// This creates a chain of trust through token embedding.
	// When B receives a token from A and wants to delegate
	// to C, B creates a new SessionTokenV2 and embeds A's token here.
	//
	// Delegation validation rules:
	// 1. Lifetime must be within origin's lifetime (exp >= origin.exp, nbf <= origin.nbf).
	// 2. Contexts must be narrowed (see contexts field validation rules).
	// 3. If origin.final is true, delegation is forbidden.
	// 4. Maximum chain depth: 4 tokens.
	Origin        *SessionTokenV2 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTokenV2) Reset() {
	*x = SessionTokenV2{}
	mi := &file_proto_session_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTokenV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTokenV2) ProtoMessage() {}

func (x *SessionTokenV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTokenV2.ProtoReflect.Descriptor instead.
func (*SessionTokenV2) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{11}
}

func (x *SessionTokenV2) GetBody() *SessionTokenV2_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SessionTokenV2) GetSignature() *refs.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SessionTokenV2) GetOrigin() *SessionTokenV2 {
	if x != nil {
		return x.Origin
	}
	return nil
}

// Carries objects involved in the object session.
type ObjectSessionContext_Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates which container the session is spread to. Field MUST be set
	// and correct.
	Container *refs.ContainerID `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// Indicates which objects the session is spread to. Objects are expected
	// to be stored in the NeoFS container referenced by `container` field.
	// Each element MUST have correct format.
	Objects       []*refs.ObjectID `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectSessionContext_Target) Reset() {
	*x = ObjectSessionContext_Target{}
	mi := &file_proto_session_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectSessionContext_Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSessionContext_Target) ProtoMessage() {}

func (x *ObjectSessionContext_Target) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSessionContext_Target.ProtoReflect.Descriptor instead.
func (*ObjectSessionContext_Target) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ObjectSessionContext_Target) GetContainer() *refs.ContainerID {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *ObjectSessionContext_Target) GetObjects() []*refs.ObjectID {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Session Token body
type SessionToken_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier is a valid UUIDv4 in binary form
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the session initiator
	OwnerId *refs.OwnerID `protobuf:"bytes,2,opt,name=owner_id,json=ownerID,proto3" json:"owner_id,omitempty"`
	// Lifetime of the session
	Lifetime *SessionToken_Body_TokenLifetime `protobuf:"bytes,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Public key used in session
	SessionKey []byte `protobuf:"bytes,4,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// Session Context information
	//
	// Types that are valid to be assigned to Context:
	//
	//	*SessionToken_Body_Object
	//	*SessionToken_Body_Container
	Context       isSessionToken_Body_Context `protobuf_oneof:"context"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken_Body) Reset() {
	*x = SessionToken_Body{}
	mi := &file_proto_session_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken_Body) ProtoMessage() {}

func (x *SessionToken_Body) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken_Body.ProtoReflect.Descriptor instead.
func (*SessionToken_Body) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SessionToken_Body) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SessionToken_Body) GetOwnerId() *refs.OwnerID {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *SessionToken_Body) GetLifetime() *SessionToken_Body_TokenLifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *SessionToken_Body) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *SessionToken_Body) GetContext() isSessionToken_Body_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SessionToken_Body) GetObject() *ObjectSessionContext {
	if x != nil {
		if x, ok := x.Context.(*SessionToken_Body_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *SessionToken_Body) GetContainer() *ContainerSessionContext {
	if x != nil {
		if x, ok := x.Context.(*SessionToken_Body_Container); ok {
			return x.Container
		}
	}
	return nil
}

type isSessionToken_Body_Context interface {
	isSessionToken_Body_Context()
}

type SessionToken_Body_Object struct {
	// ObjectService session context
	Object *ObjectSessionContext `protobuf:"bytes,5,opt,name=object,proto3,oneof"`
}

type SessionToken_Body_Container struct {
	// ContainerService session context
	Container *ContainerSessionContext `protobuf:"bytes,6,opt,name=container,proto3,oneof"`
}

func (*SessionToken_Body_Object) isSessionToken_Body_Context() {}

func (*SessionToken_Body_Container) isSessionToken_Body_Context() {}

// Lifetime parameters of the token. Field names taken from rfc7519.
type SessionToken_Body_TokenLifetime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expiration epoch, the last epoch when token is valid.
	Exp uint64 `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	// Not valid before epoch, the first epoch when token is valid.
	Nbf uint64 `protobuf:"varint,2,opt,name=nbf,proto3" json:"nbf,omitempty"`
	// Issued at Epoch
	Iat           uint64 `protobuf:"varint,3,opt,name=iat,proto3" json:"iat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken_Body_TokenLifetime) Reset() {
	*x = SessionToken_Body_TokenLifetime{}
	mi := &file_proto_session_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken_Body_TokenLifetime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken_Body_TokenLifetime) ProtoMessage() {}

func (x *SessionToken_Body_TokenLifetime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken_Body_TokenLifetime.ProtoReflect.Descriptor instead.
func (*SessionToken_Body_TokenLifetime) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *SessionToken_Body_TokenLifetime) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *SessionToken_Body_TokenLifetime) GetNbf() uint64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *SessionToken_Body_TokenLifetime) GetIat() uint64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

// Session Token body.
type SessionTokenV2_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token version.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Application-specific data that can be used to store additional context.
	// This field is optional and can contain any application-defined data.
	// Maximum size: 1024 bytes.
	Appdata []byte `protobuf:"bytes,2,opt,name=appdata,proto3" json:"appdata,omitempty"`
	// Account that issued this token (who signed it).
	Issuer *refs.OwnerID `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Accounts authorized by this token (who can use it).
	// Maximum number of subjects: 8.
	Subjects []*Target `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Lifetime of this token.
	Lifetime *TokenLifetime `protobuf:"bytes,5,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// Unified session contexts for both object and container operations.
	// Multiple contexts allow authorization for different combinations.
	//
	// Validation rules:
	//  1. Only one wildcard context (empty container ID) is allowed per token.
	//     Wildcard context must come first if present.
	//  2. Contexts must be sorted in ascending order by ContainerID.
	//  3. Duplicate containers are not allowed (each container can appear only once).
	//  4. Each context must have at least one verb (enforced by SessionContextV2).
	//  5. Verbs within each context must be sorted in ascending order (enforced by SessionContextV2).
	//  6. Maximum number of contexts: 16.
	//
	// Delegation rules (when origin token is present):
	// 1. New contexts (containers) can only be added if origin token has a wildcard context.
	// 2. All rights must be narrowed during delegation:
	//   - Verbs must be a subset of origin's verbs for the same container
	//   - Cannot add new verbs not present in origin for the same container
	Contexts []*SessionContextV2 `protobuf:"bytes,6,rep,name=contexts,proto3" json:"contexts,omitempty"`
	// final is a flag indicating whether further delegation is allowed.
	// If set to true, subjects of this token cannot delegate their rights further.
	Final         bool `protobuf:"varint,7,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTokenV2_Body) Reset() {
	*x = SessionTokenV2_Body{}
	mi := &file_proto_session_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTokenV2_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTokenV2_Body) ProtoMessage() {}

func (x *SessionTokenV2_Body) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTokenV2_Body.ProtoReflect.Descriptor instead.
func (*SessionTokenV2_Body) Descriptor() ([]byte, []int) {
	return file_proto_session_types_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SessionTokenV2_Body) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SessionTokenV2_Body) GetAppdata() []byte {
	if x != nil {
		return x.Appdata
	}
	return nil
}

func (x *SessionTokenV2_Body) GetIssuer() *refs.OwnerID {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *SessionTokenV2_Body) GetSubjects() []*Target {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SessionTokenV2_Body) GetLifetime() *TokenLifetime {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *SessionTokenV2_Body) GetContexts() []*SessionContextV2 {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *SessionTokenV2_Body) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

var File_proto_session_types_proto protoreflect.FileDescriptor

const file_proto_session_types_proto_rawDesc = "" +
	"\n" +
	"\x19proto/session/types.proto\x12\x11neo.fs.v2.session\x1a\x15proto/acl/types.proto\x1a\x16proto/refs/types.proto\x1a\x18proto/status/types.proto\"\x85\x03\n" +
	"\x14ObjectSessionContext\x12@\n" +
	"\x04verb\x18\x01 \x01(\x0e2,.neo.fs.v2.session.ObjectSessionContext.VerbR\x04verb\x12F\n" +
	"\x06target\x18\x02 \x01(\v2..neo.fs.v2.session.ObjectSessionContext.TargetR\x06target\x1aw\n" +
	"\x06Target\x129\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1b.neo.fs.v2.refs.ContainerIDR\tcontainer\x122\n" +
	"\aobjects\x18\x02 \x03(\v2\x18.neo.fs.v2.refs.ObjectIDR\aobjects\"j\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\a\n" +
	"\x03GET\x10\x02\x12\b\n" +
	"\x04HEAD\x10\x03\x12\n" +
	"\n" +
	"\x06SEARCH\x10\x04\x12\n" +
	"\n" +
	"\x06DELETE\x10\x05\x12\t\n" +
	"\x05RANGE\x10\x06\x12\r\n" +
	"\tRANGEHASH\x10\a\"\xa1\x02\n" +
	"\x17ContainerSessionContext\x12C\n" +
	"\x04verb\x18\x01 \x01(\x0e2/.neo.fs.v2.session.ContainerSessionContext.VerbR\x04verb\x12\x1a\n" +
	"\bwildcard\x18\x02 \x01(\bR\bwildcard\x12>\n" +
	"\fcontainer_id\x18\x03 \x01(\v2\x1b.neo.fs.v2.refs.ContainerIDR\vcontainerID\"e\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\v\n" +
	"\aSETEACL\x10\x03\x12\x10\n" +
	"\fSETATTRIBUTE\x10\x04\x12\x13\n" +
	"\x0fREMOVEATTRIBUTE\x10\x05\"\xa0\x04\n" +
	"\fSessionToken\x128\n" +
	"\x04body\x18\x01 \x01(\v2$.neo.fs.v2.session.SessionToken.BodyR\x04body\x127\n" +
	"\tsignature\x18\x02 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\tsignature\x1a\x9c\x03\n" +
	"\x04Body\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x122\n" +
	"\bowner_id\x18\x02 \x01(\v2\x17.neo.fs.v2.refs.OwnerIDR\aownerID\x12N\n" +
	"\blifetime\x18\x03 \x01(\v22.neo.fs.v2.session.SessionToken.Body.TokenLifetimeR\blifetime\x12\x1f\n" +
	"\vsession_key\x18\x04 \x01(\fR\n" +
	"sessionKey\x12A\n" +
	"\x06object\x18\x05 \x01(\v2'.neo.fs.v2.session.ObjectSessionContextH\x00R\x06object\x12J\n" +
	"\tcontainer\x18\x06 \x01(\v2*.neo.fs.v2.session.ContainerSessionContextH\x00R\tcontainer\x1aE\n" +
	"\rTokenLifetime\x12\x10\n" +
	"\x03exp\x18\x01 \x01(\x04R\x03exp\x12\x10\n" +
	"\x03nbf\x18\x02 \x01(\x04R\x03nbf\x12\x10\n" +
	"\x03iat\x18\x03 \x01(\x04R\x03iatB\t\n" +
	"\acontext\"1\n" +
	"\aXHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xda\x03\n" +
	"\x11RequestMetaHeader\x121\n" +
	"\aversion\x18\x01 \x01(\v2\x17.neo.fs.v2.refs.VersionR\aversion\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x127\n" +
	"\tx_headers\x18\x04 \x03(\v2\x1a.neo.fs.v2.session.XHeaderR\bxHeaders\x12D\n" +
	"\rsession_token\x18\x05 \x01(\v2\x1f.neo.fs.v2.session.SessionTokenR\fsessionToken\x12K\n" +
	"\x10session_token_v2\x18\t \x01(\v2!.neo.fs.v2.session.SessionTokenV2R\x0esessionTokenV2\x12=\n" +
	"\fbearer_token\x18\x06 \x01(\v2\x1a.neo.fs.v2.acl.BearerTokenR\vbearerToken\x12<\n" +
	"\x06origin\x18\a \x01(\v2$.neo.fs.v2.session.RequestMetaHeaderR\x06origin\x12!\n" +
	"\fmagic_number\x18\b \x01(\x04R\vmagicNumber\"\x99\x02\n" +
	"\x12ResponseMetaHeader\x121\n" +
	"\aversion\x18\x01 \x01(\v2\x17.neo.fs.v2.refs.VersionR\aversion\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x127\n" +
	"\tx_headers\x18\x04 \x03(\v2\x1a.neo.fs.v2.session.XHeaderR\bxHeaders\x12=\n" +
	"\x06origin\x18\x05 \x01(\v2%.neo.fs.v2.session.ResponseMetaHeaderR\x06origin\x120\n" +
	"\x06status\x18\x06 \x01(\v2\x18.neo.fs.v2.status.StatusR\x06status\"\xab\x02\n" +
	"\x19RequestVerificationHeader\x12@\n" +
	"\x0ebody_signature\x18\x01 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\rbodySignature\x12@\n" +
	"\x0emeta_signature\x18\x02 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\rmetaSignature\x12D\n" +
	"\x10origin_signature\x18\x03 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\x0foriginSignature\x12D\n" +
	"\x06origin\x18\x04 \x01(\v2,.neo.fs.v2.session.RequestVerificationHeaderR\x06origin\"\xad\x02\n" +
	"\x1aResponseVerificationHeader\x12@\n" +
	"\x0ebody_signature\x18\x01 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\rbodySignature\x12@\n" +
	"\x0emeta_signature\x18\x02 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\rmetaSignature\x12D\n" +
	"\x10origin_signature\x18\x03 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\x0foriginSignature\x12E\n" +
	"\x06origin\x18\x04 \x01(\v2-.neo.fs.v2.session.ResponseVerificationHeaderR\x06origin\"i\n" +
	"\x06Target\x124\n" +
	"\bowner_id\x18\x01 \x01(\v2\x17.neo.fs.v2.refs.OwnerIDH\x00R\aownerID\x12\x1b\n" +
	"\bnns_name\x18\x02 \x01(\tH\x00R\annsNameB\f\n" +
	"\n" +
	"identifier\"E\n" +
	"\rTokenLifetime\x12\x10\n" +
	"\x03exp\x18\x01 \x01(\x04R\x03exp\x12\x10\n" +
	"\x03nbf\x18\x02 \x01(\x04R\x03nbf\x12\x10\n" +
	"\x03iat\x18\x03 \x01(\x04R\x03iat\"|\n" +
	"\x10SessionContextV2\x129\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1b.neo.fs.v2.refs.ContainerIDR\tcontainer\x12-\n" +
	"\x05verbs\x18\x02 \x03(\x0e2\x17.neo.fs.v2.session.VerbR\x05verbs\"\xfa\x03\n" +
	"\x0eSessionTokenV2\x12:\n" +
	"\x04body\x18\x01 \x01(\v2&.neo.fs.v2.session.SessionTokenV2.BodyR\x04body\x127\n" +
	"\tsignature\x18\x02 \x01(\v2\x19.neo.fs.v2.refs.SignatureR\tsignature\x129\n" +
	"\x06origin\x18\x03 \x01(\v2!.neo.fs.v2.session.SessionTokenV2R\x06origin\x1a\xb7\x02\n" +
	"\x04Body\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x18\n" +
	"\aappdata\x18\x02 \x01(\fR\aappdata\x12/\n" +
	"\x06issuer\x18\x03 \x01(\v2\x17.neo.fs.v2.refs.OwnerIDR\x06issuer\x125\n" +
	"\bsubjects\x18\x04 \x03(\v2\x19.neo.fs.v2.session.TargetR\bsubjects\x12<\n" +
	"\blifetime\x18\x05 \x01(\v2 .neo.fs.v2.session.TokenLifetimeR\blifetime\x12?\n" +
	"\bcontexts\x18\x06 \x03(\v2#.neo.fs.v2.session.SessionContextV2R\bcontexts\x12\x14\n" +
	"\x05final\x18\a \x01(\bR\x05final*\x96\x02\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"OBJECT_PUT\x10\x01\x12\x0e\n" +
	"\n" +
	"OBJECT_GET\x10\x02\x12\x0f\n" +
	"\vOBJECT_HEAD\x10\x03\x12\x11\n" +
	"\rOBJECT_SEARCH\x10\x04\x12\x11\n" +
	"\rOBJECT_DELETE\x10\x05\x12\x10\n" +
	"\fOBJECT_RANGE\x10\x06\x12\x14\n" +
	"\x10OBJECT_RANGEHASH\x10\a\x12\x11\n" +
	"\rCONTAINER_PUT\x10\b\x12\x14\n" +
	"\x10CONTAINER_DELETE\x10\t\x12\x15\n" +
	"\x11CONTAINER_SETEACL\x10\n" +
	"\x12\x1a\n" +
	"\x16CONTAINER_SETATTRIBUTE\x10\v\x12\x1d\n" +
	"\x19CONTAINER_REMOVEATTRIBUTE\x10\fBOZ/github.com/nspcc-dev/neofs-sdk-go/proto/session\xaa\x02\x1bNeo.FileStorage.API.Sessionb\x06proto3"

var (
	file_proto_session_types_proto_rawDescOnce sync.Once
	file_proto_session_types_proto_rawDescData []byte
)

func file_proto_session_types_proto_rawDescGZIP() []byte {
	file_proto_session_types_proto_rawDescOnce.Do(func() {
		file_proto_session_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_types_proto_rawDesc), len(file_proto_session_types_proto_rawDesc)))
	})
	return file_proto_session_types_proto_rawDescData
}

var file_proto_session_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_session_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_session_types_proto_goTypes = []any{
	(Verb)(0),                               // 0: neo.fs.v2.session.Verb
	(ObjectSessionContext_Verb)(0),          // 1: neo.fs.v2.session.ObjectSessionContext.Verb
	(ContainerSessionContext_Verb)(0),       // 2: neo.fs.v2.session.ContainerSessionContext.Verb
	(*ObjectSessionContext)(nil),            // 3: neo.fs.v2.session.ObjectSessionContext
	(*ContainerSessionContext)(nil),         // 4: neo.fs.v2.session.ContainerSessionContext
	(*SessionToken)(nil),                    // 5: neo.fs.v2.session.SessionToken
	(*XHeader)(nil),                         // 6: neo.fs.v2.session.XHeader
	(*RequestMetaHeader)(nil),               // 7: neo.fs.v2.session.RequestMetaHeader
	(*ResponseMetaHeader)(nil),              // 8: neo.fs.v2.session.ResponseMetaHeader
	(*RequestVerificationHeader)(nil),       // 9: neo.fs.v2.session.RequestVerificationHeader
	(*ResponseVerificationHeader)(nil),      // 10: neo.fs.v2.session.ResponseVerificationHeader
	(*Target)(nil),                          // 11: neo.fs.v2.session.Target
	(*TokenLifetime)(nil),                   // 12: neo.fs.v2.session.TokenLifetime
	(*SessionContextV2)(nil),                // 13: neo.fs.v2.session.SessionContextV2
	(*SessionTokenV2)(nil),                  // 14: neo.fs.v2.session.SessionTokenV2
	(*ObjectSessionContext_Target)(nil),     // 15: neo.fs.v2.session.ObjectSessionContext.Target
	(*SessionToken_Body)(nil),               // 16: neo.fs.v2.session.SessionToken.Body
	(*SessionToken_Body_TokenLifetime)(nil), // 17: neo.fs.v2.session.SessionToken.Body.TokenLifetime
	(*SessionTokenV2_Body)(nil),             // 18: neo.fs.v2.session.SessionTokenV2.Body
	(*refs.ContainerID)(nil),                // 19: neo.fs.v2.refs.ContainerID
	(*refs.Signature)(nil),                  // 20: neo.fs.v2.refs.Signature
	(*refs.Version)(nil),                    // 21: neo.fs.v2.refs.Version
	(*acl.BearerToken)(nil),                 // 22: neo.fs.v2.acl.BearerToken
	(*status.Status)(nil),                   // 23: neo.fs.v2.status.Status
	(*refs.OwnerID)(nil),                    // 24: neo.fs.v2.refs.OwnerID
	(*refs.ObjectID)(nil),                   // 25: neo.fs.v2.refs.ObjectID
}
var file_proto_session_types_proto_depIdxs = []int32{
	1,  // 0: neo.fs.v2.session.ObjectSessionContext.verb:type_name -> neo.fs.v2.session.ObjectSessionContext.Verb
	15, // 1: neo.fs.v2.session.ObjectSessionContext.target:type_name -> neo.fs.v2.session.ObjectSessionContext.Target
	2,  // 2: neo.fs.v2.session.ContainerSessionContext.verb:type_name -> neo.fs.v2.session.ContainerSessionContext.Verb
	19, // 3: neo.fs.v2.session.ContainerSessionContext.container_id:type_name -> neo.fs.v2.refs.ContainerID
	16, // 4: neo.fs.v2.session.SessionToken.body:type_name -> neo.fs.v2.session.SessionToken.Body
	20, // 5: neo.fs.v2.session.SessionToken.signature:type_name -> neo.fs.v2.refs.Signature
	21, // 6: neo.fs.v2.session.RequestMetaHeader.version:type_name -> neo.fs.v2.refs.Version
	6,  // 7: neo.fs.v2.session.RequestMetaHeader.x_headers:type_name -> neo.fs.v2.session.XHeader
	5,  // 8: neo.fs.v2.session.RequestMetaHeader.session_token:type_name -> neo.fs.v2.session.SessionToken
	14, // 9: neo.fs.v2.session.RequestMetaHeader.session_token_v2:type_name -> neo.fs.v2.session.SessionTokenV2
	22, // 10: neo.fs.v2.session.RequestMetaHeader.bearer_token:type_name -> neo.fs.v2.acl.BearerToken
	7,  // 11: neo.fs.v2.session.RequestMetaHeader.origin:type_name -> neo.fs.v2.session.RequestMetaHeader
	21, // 12: neo.fs.v2.session.ResponseMetaHeader.version:type_name -> neo.fs.v2.refs.Version
	6,  // 13: neo.fs.v2.session.ResponseMetaHeader.x_headers:type_name -> neo.fs.v2.session.XHeader
	8,  // 14: neo.fs.v2.session.ResponseMetaHeader.origin:type_name -> neo.fs.v2.session.ResponseMetaHeader
	23, // 15: neo.fs.v2.session.ResponseMetaHeader.status:type_name -> neo.fs.v2.status.Status
	20, // 16: neo.fs.v2.session.RequestVerificationHeader.body_signature:type_name -> neo.fs.v2.refs.Signature
	20, // 17: neo.fs.v2.session.RequestVerificationHeader.meta_signature:type_name -> neo.fs.v2.refs.Signature
	20, // 18: neo.fs.v2.session.RequestVerificationHeader.origin_signature:type_name -> neo.fs.v2.refs.Signature
	9,  // 19: neo.fs.v2.session.RequestVerificationHeader.origin:type_name -> neo.fs.v2.session.RequestVerificationHeader
	20, // 20: neo.fs.v2.session.ResponseVerificationHeader.body_signature:type_name -> neo.fs.v2.refs.Signature
	20, // 21: neo.fs.v2.session.ResponseVerificationHeader.meta_signature:type_name -> neo.fs.v2.refs.Signature
	20, // 22: neo.fs.v2.session.ResponseVerificationHeader.origin_signature:type_name -> neo.fs.v2.refs.Signature
	10, // 23: neo.fs.v2.session.ResponseVerificationHeader.origin:type_name -> neo.fs.v2.session.ResponseVerificationHeader
	24, // 24: neo.fs.v2.session.Target.owner_id:type_name -> neo.fs.v2.refs.OwnerID
	19, // 25: neo.fs.v2.session.SessionContextV2.container:type_name -> neo.fs.v2.refs.ContainerID
	0,  // 26: neo.fs.v2.session.SessionContextV2.verbs:type_name -> neo.fs.v2.session.Verb
	18, // 27: neo.fs.v2.session.SessionTokenV2.body:type_name -> neo.fs.v2.session.SessionTokenV2.Body
	20, // 28: neo.fs.v2.session.SessionTokenV2.signature:type_name -> neo.fs.v2.refs.Signature
	14, // 29: neo.fs.v2.session.SessionTokenV2.origin:type_name -> neo.fs.v2.session.SessionTokenV2
	19, // 30: neo.fs.v2.session.ObjectSessionContext.Target.container:type_name -> neo.fs.v2.refs.ContainerID
	25, // 31: neo.fs.v2.session.ObjectSessionContext.Target.objects:type_name -> neo.fs.v2.refs.ObjectID
	24, // 32: neo.fs.v2.session.SessionToken.Body.owner_id:type_name -> neo.fs.v2.refs.OwnerID
	17, // 33: neo.fs.v2.session.SessionToken.Body.lifetime:type_name -> neo.fs.v2.session.SessionToken.Body.TokenLifetime
	3,  // 34: neo.fs.v2.session.SessionToken.Body.object:type_name -> neo.fs.v2.session.ObjectSessionContext
	4,  // 35: neo.fs.v2.session.SessionToken.Body.container:type_name -> neo.fs.v2.session.ContainerSessionContext
	24, // 36: neo.fs.v2.session.SessionTokenV2.Body.issuer:type_name -> neo.fs.v2.refs.OwnerID
	11, // 37: neo.fs.v2.session.SessionTokenV2.Body.subjects:type_name -> neo.fs.v2.session.Target
	12, // 38: neo.fs.v2.session.SessionTokenV2.Body.lifetime:type_name -> neo.fs.v2.session.TokenLifetime
	13, // 39: neo.fs.v2.session.SessionTokenV2.Body.contexts:type_name -> neo.fs.v2.session.SessionContextV2
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_proto_session_types_proto_init() }
func file_proto_session_types_proto_init() {
	if File_proto_session_types_proto != nil {
		return
	}
	file_proto_session_types_proto_msgTypes[8].OneofWrappers = []any{
		(*Target_OwnerId)(nil),
		(*Target_NnsName)(nil),
	}
	file_proto_session_types_proto_msgTypes[13].OneofWrappers = []any{
		(*SessionToken_Body_Object)(nil),
		(*SessionToken_Body_Container)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_types_proto_rawDesc), len(file_proto_session_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_session_types_proto_goTypes,
		DependencyIndexes: file_proto_session_types_proto_depIdxs,
		EnumInfos:         file_proto_session_types_proto_enumTypes,
		MessageInfos:      file_proto_session_types_proto_msgTypes,
	}.Build()
	File_proto_session_types_proto = out.File
	file_proto_session_types_proto_goTypes = nil
	file_proto_session_types_proto_depIdxs = nil
}
